index_cover: img/home-bg.jpg
google_analytics: null
twitter_url: null
gitlab_url: null
linkedin_url: null
mailto: null
twitter_handle: null
github_url: ""
comments:
  disqus_shortname: null
  facebook:
    appid: null
    comment_count: 5
    comment_colorscheme: light
favicon: null
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  Github:
    url: https://github.com/klugjo/hexo-theme-clean-blog
    icon: github
menu_title: Configurable Title
default_post_title: Untitled
facebook_url: null
addthis: null
