# Netlify build configuration
[build]
  command = "npm install && npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "22.21.0"

# Branch deploy configuration
[context.staging]
  command = "npm install && npm run build"

[context.branch-deploy]
  command = "npm install && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
